[workspace]
authors = ["π12Qα <41827134+firqaaa@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "p14"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = "25.6.*"
